kasketis/netfox

- netfox/NFXBodyDetailsController.swift
- netfox/NFXHTTPModel.swift
I've moved the pretty printing of JSON into the model so it's not only valid on responses > 1024 bytes of data.
We now check the content type of the response before attempting to pretty print the data by converting to a simple enum. This could be extended in the future to include other content types (html / xml / images / e.t.c)
In theory this should work for both requests and responses but for some reason I'm not able to see my JSON request bodies (I'm currently trying to figure out why as it might be an Alamofire issue?) so if someone else could test that would be fantastic
> Pretty Print JSON responses

- netfox/NFXHelper.swift
NFXBody will now check the NSURLProtocol for if a value is set for the body data.
This is to work around a problem where by the time NSURLProtocol.startLoading is called, the HTTPBody of the request and canonical request will both be nil
If you don't set the NFXBodyData property then it will be ignored and defaulted to the original behaviour of returning NSData()
If you want to log request data you should do something like the following:
```
if let bodyData = mutableURLRequest.HTTPBody {
NSURLProtocol.setProperty(bodyData, forKey: "NFXBodyData", inRequest: mutableURLRequest)
}
```
Wherever you construct your NSMutableURLRequest's (for instance when using Alamofire - in URLRequest of URLRequestConvertible)
See: http://openradar.appspot.com/15993891
> Workaround for issue #16

- netfox/NFXHTTPModel.swift
The content type for the request wasn't being stored so it was never treated as JSON and pretty printed.
We now store the content type for every request and format it using the same prettyOutput method as the responses
> Pretty printing now works on requests

- Workarounds.md
When using Alamofire with a custom Manager the default headers were not being sent with every request
Updated the documentation to include the fact that you should also include the default HTTP headers when using Alamofire
> Default headers not sent when using Alamofire with integration from workarounds

- netfox/NFX.swift
A bug exists where it's possible to end up with multiple copies of the debug view controller presented.
It's easiest to reproduce in the simulator if you press ctrl+cmd+z twice in quick succession
It occurs because we don't mark the view controller as being presented until the animation has completed so if you trigger another presentation whilst it's animating it will attempt to present another version
I've fixed the issue by simply moving the boolean check before the completion callback - so we block any new presentations whilst we have allocated a new navigation controller for presentation
hideNFX is still correct by setting this boolean in the animation completion block since we should still block new presentations until it' finished being dismissed
> Duplicate versions netfox may be displayed (if you're super quick)

- netfox/NFXSettingsController.swift
UIAlertController needs a sourceView and a sourceRect when using UIAlertControllerStyleActionSheet style on the iPad.
Related Crash info:
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x12ed9f130>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method …
> Fix iPad crash when tapping on clear button

- netfox/NFXHTTPModel.swift
Parsing JSON with AllowFragments returns nil on non-json data without throwing an error. That causes dataWithJSONObject to crash with:
NSInvalidArgumentException, reason: *** +[NSJSONSerialization dataWithJSONObject:options:error:]: Invalid top-level type in JSON write
> Fixes crash trying to pretty print invalid JSON

- netfox/NFXProtocol.swift
This fixes the issue where requests don't get logged if they are using NSURLSessionTasks. Please see issue https://github.com/kasketis/netfox/issues/32.
There are a couple of caveats. If you are using NSURLSessionTasks you must add the NSXProtocol to the protocolClasses on the NSUserSessionConfiguration.
For example:
**Obj-C**
```
NSURLSessionConfiguration* config = NSURLSessionConfiguration.defaultSessionConfiguration;
config.protocolClasses = @[[NFXProtocol class]];
```
**Swift**
```
let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
configuration.protocolClasses?.insert(NFXProtocol.self, atIndex: 0)
```
If someone has any ideas how we can accomplish loving these requests without setting the protocolClasses, please leave a comment.
> ADD: Support for NSURLSessionTasks

- netfox/NFXDetailsController.swift
- netfox/NFXRawBodyDetailsController.swift
With devices on RTL some texts get wrong alignment. Since "details"  always will be english, `text Alignment` maybe hardcoded with `.Left`
> FIX: Text alignment

- netfox/NFX.swift
Post notifications when opening/closing NetFox, for benefit of hosting apps that want to log this. I did not want to interfere with existing code/notifications, but it probably would be better to replace that "NFXDeactivateSearch" notification with the new nfxWillCloseNotification.
> Post notifications for opening/closing NetFox

- netfox.podspec
There was some issue in the podspec which was making the pod not usable for macOS. That PR should fix them. Until now we were still using our own clone of netfox, but we'd like to move on the main repository once that PR merged.
I didn't forget about the gif you asked, but in order to do it, the best way should be to add a demo project to netfox directly. Since I can't share our API logs (private stuff), that could be a nice way to handle the issue.
Also, just a suggestion, do you mind to add some contributors to the project? There are some PRs / fixed that look pretty interesting. Mainly the ones which migrate netfox to Swift 2.{2,3}. It would be for the best if netfox can support swift 3 before it's released!
> Fix macOS podspec

- netfox/Core/NFXHTTPModel.swift
This PR detects [JSON API](http://jsonapi.org/format/) headers (e.g. application/vnd.api+json) as JSON APIs in order for them to be parsed & presented correctly.
> Support JSON API headers  (application/vnd.api+json)

- netfox/Core/NFX.swift
- netfox/Core/NFXAssets.swift
- netfox/Core/NFXHelper.swift
- netfox/iOS/NFXListController_iOS.swift
This PR adds a close button to the top-left of the Search bar on the list controller. 
This is needed specifically if using a custom gesture. For example, if you use a 3-finger-swipe on your UIWindow to show Netfox, you will have no way to hide it since that Gesture recognizer only applies to the App’s window. 
I’ve also 
- Added NFX.toggle() that does a show/hide based on presentation status
- Removed the dependency on the “custom” gesture for show/hide - I don’t think only custom gestures would be interested in showing and hiding the controller.
> Added left close button in NFXListController_iOS + NFX.toggle()

- netfox/Core/NFXGenericController.swift
Fix warning : 'characters' is deprecated: Please use String or Substring directly
> Fix warning on NFXGenericController.swift

- netfox/Core/NFX.swift
`NFX.sharedInstance()` was inaccessible in ObjC when the project was mixed with Swift 4.  This small PR fixes that.
> `NFX.sharedInstance()` accessibility in ObjC when mixed with Swift 4

- netfox.podspec
- netfox/NFX.swift
- netfox/NFXHTTPModel.swift
- netfox/NFXHTTPModelManager.swift
As marked in issue https://github.com/kasketis/netfox/issues/53, caching will be disabled by using the `NFXProtocol`. 
To fix this I wrote a plugin for our Moya library, which uses the methods which are changed to public:
```
import Moya
import Result
import netfox
public typealias TIFEndpointClosure = TIFAPI -> NSURLRequest
public final class TIFNetfoxPlugin {
var modelsDict = [Int: NFXHTTPModel]()
let endpointClosure:TIFEndpointClosure
public init(endpointClosure:TIFEndpointClosure){
self.endpointClosure = endpointClosure
}
}
extension TIFNetfoxPlugin : PluginType {
/// Called by the provider as soon as the request is about to start
public func willSendRequest(request: RequestType, target: TargetType) {
guard let tifTarget = target as? TIFAPI else { return }
let urlRequest = …
```
> Making it possible to manually save requests and responses

- netfox/Core/NFXHTTPModel.swift
- netfox/Core/NFXProtocol.swift
I separated the saving of http request body from the saving of other request properties in NFXHTTPModel.saveRequest(request: URLRequest) to avoid concurrent reads from httpBodyStream. The request body is saved only after the response is received. If two threads read concurrently from the same InputStream, both of them will get incomplete data. 
The change might also fix this issue: 
[https://github.com/kasketis/netfox/issues/116](url)
> Fixed request timeouts when sending multipart/form-data

- .travis.yml
- README.md
- netfox.podspec
- netfox/Core/NFX.swift
- netfox/Core/NFXGenericController.swift
- netfox/OSX/NFXListController_OSX.swift
- netfox/OSX/NFXSettingsController_OSX.swift
- netfox/iOS/NFXDetailsController_iOS.swift
- netfox/iOS/NFXHelper_iOS.swift
- netfox/iOS/NFXListCell_iOS.swift
- netfox/iOS/NFXSettingsController_iOS.swift
~~Fixing the entire code base to support both Swift 4, Swift 4.1 and Swift 4.2 will be a bit of a lengthy process.~~
~~For the meanwhile, though, explicitly setting `swift_version` to `4.0` will allow you to install netfox as part of a Xcode 10 project with no issues.~~
Well, eventually I just added support for both Swift 4 and Swift 4.2. 
This PR also gets rid of Swift 3 support, as users who still use it can target older tags/releases.
> Xcode 10 - Swift 4 & Swift 4.2

- netfox/Core/NFXGenericController.swift
- netfox/iOS/NFXListController_iOS.swift
Steps to reproduce:
Use search to filter requests list. Tap on one search result > use long press in a details screen to copy the response. "Text Copied!" alert is not visible. Closing Netfox results in a crash.
> Fixed presenting UIAlertController while using search functionality on iOS.

- netfox/iOS/NFXDetailsController_iOS.swift
Steps to reproduce:
Tap on a Share button in a details screen on iPad.
> Fixed iPad crashes after presenting popovers.

- netfox/Core/NFXAuthenticationChallengeSender.swift
- netfox/Core/NFXProtocol.swift
With the current implementation, using the `URLSession` call with `completionHandler` to perform requests, delegate callbacks are never executed (just check the documentation of `URLSession`). This results in for example redirection not working properly anymore with delegate callbacks. This pull request fixes this by handling all delegate calls properly and not using the `completionHandler` method.
> Updated NFXProtocol for handling delegate callbacks

- netfox/Core/NFX.swift
Added isStarted func to get "started" variable's value. It may be needed to implement a switch for starting/stopping NFX by a library's client.
> Fix for issue #162

- netfox/Core/NFX.swift
- netfox/iOS/NFXListController_iOS.swift
Fixed an issue where `presented` was not `false` when the new iOS 13 semi modal is closed by scrolling.
> Fixes problem of scrolling closure of Semi Modal on iOS 13

- netfox/Core/NFX.swift
- netfox/iOS/NFXListController_iOS.swift
The PR #172 solved an issue where presented was not false when the new iOS 13 semi modal is closed by scrolling, but unfortunately it created another issue. The Netfox can't be dismissed after navigate to a call, and then get back, described on issue #179.
With this approach i believe the two issues will be resolved.
What do you guys think?
> Fix for issue #179: netfox can't be dismissed after navigate to a call

- netfox/Core/NFXProtocol.swift
Mojio team noticed memory leaks within the networking layer with `netfox` integrated for debugging purposes. After this fix, we no longer see the memory leaks.
You can test this by looking at the memory graph before/after this fix.
Also, from the `URLSession` documentation:
> Important
> The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you don’t invalidate the session, your app leaks memory until the app terminates.
> Fix memory leaks by invalidating session after cancelling tasks

- netfox/Core/NFX.swift
- netfox/Core/NFXGenericController.swift
- netfox/Core/NFXHTTPModelManager.swift
- netfox/Core/NFXHelper.swift
- netfox/Core/NFXListController.swift
- netfox/Core/NFXProtocol.swift
- netfox/Core/NFXSettingsController.swift
- netfox/Core/NFXStatisticsController.swift
- netfox/OSX/NFXListController_OSX.swift
- netfox/OSX/NFXSettingsController_OSX.swift
- netfox/OSX/NFXStatisticsController_OSX.swift
- netfox/OSX/NetfoxWindow.xib
- netfox/iOS/NFXDetailsController_iOS.swift
- netfox/iOS/NFXHelper_iOS.swift
- netfox/iOS/NFXListCell_iOS.swift
- netfox/iOS/NFXListController_iOS.swift
- netfox/iOS/NFXSettingsController_iOS.swift
- netfox/iOS/NFXStatisticsController_iOS.swift
* Refactored request models management (should be more simplified and stable)
* Refactored requests list data source
* Fixed issue with temp directory removing after clearing all data
* Removed old Swift checks
* Minor code refactoring (empty lines, not necessary `swift.` prefixes, etc)
Should fix https://github.com/kasketis/netfox/issues/214 ,  https://github.com/kasketis/netfox/issues/154
> Refactoring UI part
